- name: Demo on variables
  hosts: localhost
  connection: local
  vars:
    URL: vars.google.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}


# Here in the above msg line, we have th vle

- name: Demo on variables
  hosts: localhost
  connection: local
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.google.com


- name: Demo on variables - Role variables
  hosts: localhost
  connection: local
  roles:
    - sample


## Precedence
# 1. CLI
# 2. Tasks
# 3. Roles- vars
# 4. Playbook - Play vars
# 5. Roles - defaults